name: Build & Commit Message Lint

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Next.js & Check commit messages
    runs-on: ubuntu-latest
    environment: Preview
    env:
      GH_PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          filter: 'tree:0'
          fetch-depth: '0'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn

      - name: Next.js Cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.next/cache
          key: nextjs-cache-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-source-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: nextjs-cache-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn exec eslint .

      - name: Test
        run: yarn test
        env:
          NEXT_PUBLIC_API_ENDPOINT: ${{ vars.NEXT_PUBLIC_API_ENDPOINT }}
          NEXT_PUBLIC_AGGRID_LICENSE: ${{ secrets.NEXT_PUBLIC_AGGRID_LICENSE }}

      - name: Build
        run: yarn build
        env:
          NEXT_PUBLIC_API_ENDPOINT: ${{ vars.NEXT_PUBLIC_API_ENDPOINT }}
          NEXT_PUBLIC_AGGRID_LICENSE: ${{ secrets.NEXT_PUBLIC_AGGRID_LICENSE }}

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
        run: yarn exec commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate pull request commits with commitlint
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        run: yarn exec commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Validate pull request title with commitlint
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        run: echo "${{ github.event.pull_request.title }}" | yarn exec commitlint --verbose
